<a href="https://colab.research.google.com/github/expeditive/pylibraries/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#numpy
##advantages of numpy


1.   math operations
2.   faster operations




In [ ]:
import numpy as np

list vs numpy time taken

In [ ]:
from time import process_time

time taken by a list

In [ ]:
python_list = [i for i in range(10000)]
start_time = process_time()
python_list = [i+5 for i in python_list]
end_time = process_time()

time_taken = (end_time - start_time)
print(time_taken)

0.0004618449999966856


In [ ]:
np_array = np.array([i for i in range(10000)])
start_time = process_time()
np_array += 5
end_time = process_time()

print(end_time-start_time)

0.00019225699999836365


In [ ]:
#list
list1 = [ 1, 3, 6, 8, 9]
print(list1)
type(list1)

[1, 3, 6, 8, 9]


list

In [ ]:
#numpy array
np_array = np.array([1, 3, 6, 8, 9])
print(np_array)
type(np_array)

[1 3 6 8 9]


numpy.ndarray

In [ ]:
#creating  a 1d array as nupmy array are generating a matrice
a = np.array([1,5,7,2])
print(a)
a.shape

[1 5 7 2]


(4,)

In [ ]:
#creating a two dimensional array
b = np.array([(1,2,4),(3,8,5)])
print(b)
b.shape

[[1 2 4]
 [3 8 5]]


(2, 3)

In [ ]:
#specifying data type
c = np.array([(1,2,5),(7,2,9)],dtype = float)
print(c)

[[1. 2. 5.]
 [7. 2. 9.]]


##initial placeholder in numpy array

In [ ]:
#creating a numpy array with initials zero
z = np.zeros((3,3))
print(z)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
o = np.ones((2,3))
print(o)

[[1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
#array of a particular value
s = np.full((5,4),7)
print(s)

[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]


In [ ]:
#creating an identity matrix
a = np.eye(4)
print(a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
#creating array with random values
b = np.random.random((3,4))
print(b)

[[0.40303553 0.73387386 0.02673812 0.09761266]
 [0.89013747 0.69230651 0.22997261 0.68216554]
 [0.61494588 0.34035598 0.50318991 0.59311891]]


In [ ]:
#creating random values but within specific range
b = np.random.randint(10,35,(3,3))
print(b)

[[12 21 25]
 [24 23 20]
 [14 14 13]]


In [ ]:
# array of evenly spaced values --> specifying the numbers of values required
d = np.linspace(10,30,5)
print(d)

[10. 15. 20. 25. 30.]


In [ ]:
#array of evenly spaced values --> specifying the steps
e = np.arange(10,35,5)
print(e)

[10 15 20 25 30]


In [ ]:
#converting  list to numpy array
list2 = [1,9,2,8,4,7]
np_array = np.asarray(list2)
print(np_array)
type(np_array)

[1 9 2 8 4 7]


numpy.ndarray

##analysing a numpy array

In [ ]:
c = np.random.randint(10,90,(5,5))
print(c)

[[74 50 73 29 33]
 [43 48 63 89 83]
 [45 84 22 38 28]
 [51 26 27 66 39]
 [79 81 76 19 69]]


In [ ]:
#array dimensions
print(c.shape)

(5, 5)


In [ ]:
#number of dimensions
print(c.ndim)

2


In [ ]:
#number of elements in a array
print(c.size)

25


In [ ]:
#checking dta type
print(c.dtype)

int64


##maths operations



In [ ]:
list1 = [1,6,3,8,3]
list2 = [2,9,4,1,8]
print(list1 + list2) #concatenation happens here

[1, 6, 3, 8, 3, 2, 9, 4, 1, 8]


In [ ]:
a = np.random.randint(12,38,(4,4))
b = np.random.randint(34,56,(4,4))
print(a)
print(b)

[[29 36 20 34]
 [18 35 30 34]
 [26 16 18 17]
 [23 27 32 23]]
[[47 47 43 55]
 [54 37 39 44]
 [47 53 44 52]
 [36 49 37 41]]


In [ ]:
print(a+b)
print(a-b)
print(a/b)
print(a*b)

[[76 83 63 89]
 [72 72 69 78]
 [73 69 62 69]
 [59 76 69 64]]
[[-18 -11 -23 -21]
 [-36  -2  -9 -10]
 [-21 -37 -26 -35]
 [-13 -22  -5 -18]]
[[0.61702128 0.76595745 0.46511628 0.61818182]
 [0.33333333 0.94594595 0.76923077 0.77272727]
 [0.55319149 0.30188679 0.40909091 0.32692308]
 [0.63888889 0.55102041 0.86486486 0.56097561]]
[[1363 1692  860 1870]
 [ 972 1295 1170 1496]
 [1222  848  792  884]
 [ 828 1323 1184  943]]


In [ ]:
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))

[[76 83 63 89]
 [72 72 69 78]
 [73 69 62 69]
 [59 76 69 64]]
[[-18 -11 -23 -21]
 [-36  -2  -9 -10]
 [-21 -37 -26 -35]
 [-13 -22  -5 -18]]
[[1363 1692  860 1870]
 [ 972 1295 1170 1496]
 [1222  848  792  884]
 [ 828 1323 1184  943]]
[[0.61702128 0.76595745 0.46511628 0.61818182]
 [0.33333333 0.94594595 0.76923077 0.77272727]
 [0.55319149 0.30188679 0.40909091 0.32692308]
 [0.63888889 0.55102041 0.86486486 0.56097561]]


##array manipulation

In [ ]:
array=np.random.randint(0,10,(2,3))
print(array)
print(array.shape)

[[8 8 0]
 [4 0 9]]
(2, 3)


In [ ]:
#transpose
trans= np.transpose(array)
print(trans)
print(trans.shape)

[[8 4]
 [8 0]
 [0 9]]
(3, 2)


In [ ]:
trans2 = array.T
print(trans2)
print(trans2.shape)

[[8 4]
 [8 0]
 [0 9]]
(3, 2)


In [ ]:
#reshaping a array
a =np.random.randint(0,10,(2,3))
print(a)
print(a.shape)


[[9 1 4]
 [0 6 1]]
(2, 3)


In [ ]:
b = a.reshape(3,2)
print(b)
print(b.shape)

[[9 1]
 [4 0]
 [6 1]]
(3, 2)
